import { describe, expect, it } from "vitest";
import { applyNormalizationInEmulator, LegacyRecord, planNormalization } from "../normalization";

const owner = "human_fixture_owner";
const legacy = (overrides: Partial<LegacyRecord> = {}): LegacyRecord => ({ entityType: "workout", globalId: "workout_1", humanUserId: owner, revision: 1, schemaVersion: "humanv1.workout/1", contentClass: "LEGACY_NORMALIZABLE", payload: { schemaVersion: "humanv1.workout/1", workoutId: "workout_1", description: "", blocks: [{ blockId: "b1" }] }, ...overrides });

describe("deterministic normalization planner", () => {
  it("plans only meaning-preserving field and blank normalization", () => { const plan = planNormalization(owner, [legacy()]); expect(plan.classifications.SAFE_NORMALIZATION_AVAILABLE).toBe(1); expect(plan.commands[0].changes.map(item => item.fieldPath)).toEqual(["workoutGlobalId", "schemaVersion", "description"]); });
  it("rejects parent-only Pull Day and Push Day for user review without invented prescriptions", () => { const records = [legacy({ globalId: "template_d0333e99e198", payload: { workoutId: "template_d0333e99e198", blocks: [] }, contentClass: "LEGACY_INCOMPLETE" }), legacy({ globalId: "template_push", payload: { workoutId: "template_push", blocks: [] }, contentClass: "LEGACY_INCOMPLETE" })]; const plan = planNormalization(owner, records); expect(plan.classifications.USER_REVIEW_REQUIRED).toBe(2); expect(plan.commands.every(item => !item.after && item.changes.length === 0)).toBe(true); expect(plan.commands.every(item => item.reviewIssues[0].includes("blocks"))).toBe(true); });
  it("classifies ownership, revision, schema, and historical records independently", () => { const plan = planNormalization(owner, [legacy({ globalId: "other", humanUserId: "human_other" }), legacy({ globalId: "newer", remoteRevision: 2 }), legacy({ globalId: "unknown", schemaVersion: "future/99" }), legacy({ entityType: "historical", globalId: "done", contentClass: "HISTORICAL_EXECUTION" })]); expect(plan.classifications).toMatchObject({ OWNERSHIP_CONFLICT: 1, REVISION_CONFLICT: 1, UNSUPPORTED_SCHEMA: 1, HISTORICAL_PRESERVE_ONLY: 1 }); });
  it("collapses duplicate identical input and quarantines competing payloads", () => { expect(planNormalization(owner, [legacy(), legacy()]).commands).toHaveLength(1); const conflict = planNormalization(owner, [legacy(), legacy({ payload: { workoutId: "workout_1", blocks: [{ blockId: "different" }] } })]); expect(conflict.commands).toHaveLength(1); expect(conflict.commands[0].classification).toBe("REVISION_CONFLICT"); });
  it("keeps dry-run and emulator apply projections equal", () => { const plan = planNormalization(owner, [legacy()]); const result = applyNormalizationInEmulator(plan, [legacy()], true, "2026-09-14T00:00:00.000Z"); expect(result.records[0]).toEqual(plan.commands[0].after); expect(result.audits).toHaveLength(1); expect(plan.mode).toBe("DRY_RUN"); });
  it("is idempotent on a second emulator apply", () => { const plan = planNormalization(owner, [legacy()]); const first = applyNormalizationInEmulator(plan, [legacy()], true, "2026-09-14T00:00:00.000Z"); const second = applyNormalizationInEmulator(plan, first.records, true, "2026-09-14T00:00:00.000Z"); expect(second.records).toEqual(first.records); expect(second.audits).toEqual([]); });
  it("refuses all non-emulator application", () => { expect(() => applyNormalizationInEmulator(planNormalization(owner, [legacy()]), [legacy()], false, "2026-09-14T00:00:00.000Z")).toThrow("PRODUCTION_MIGRATION_DISABLED"); });
  it("never writes a cross-owner record", () => { const other = legacy({ humanUserId: "human_other" }); const plan = planNormalization(owner, [other]); expect(plan.commands[0].classification).toBe("OWNERSHIP_CONFLICT"); expect(applyNormalizationInEmulator(plan, [other], true, "2026-09-14T00:00:00.000Z")).toEqual({ records: [other], audits: [] }); });
});
