import { useState } from "react";
import { triathlonResearchDataset, triathlonResearchPlans, type ResearchPlan } from "../../fixtures/triathlonResearchFixtures";
import { buildPhaseTimeline, formatPhaseWeeks } from "../../domain/planPhaseTimeline";
import { evidenceDirectnessLabel, evidenceVerificationLabel, presentationSafePhasePurpose, researchSessionPresentation } from "../../domain/researchPlanPresentation";

const disciplineFields = [["Swim", "swimMinutes"], ["Bike", "bikeMinutes"], ["Run", "runMinutes"], ["Strength", "strengthMinutes"], ["Multisport", "multisportMinutes"], ["Recovery", "recoveryMinutes"]] as const;
export function TriathlonResearchLibrary({ onClone, mutationDisabled = false }: { onClone: (plan: ResearchPlan) => void | Promise<void>; mutationDisabled?: boolean }) {
  const [selected, setSelected] = useState(triathlonResearchPlans[0].planId);
  const [confirming, setConfirming] = useState(false);
  const [pending, setPending] = useState(false);
  const plan = triathlonResearchPlans.find(item => item.planId === selected)!;
  const phaseTimeline = buildPhaseTimeline(plan, "RESEARCH_CANDIDATE");
  const totals = Object.fromEntries(disciplineFields.map(([label, field]) => [label, plan.weeks.reduce((sum, week) => sum + week[field], 0)]));
  const activeDisciplineFields = disciplineFields.filter(([label]) => totals[label] > 0);
  return <section aria-labelledby="research-library-title" className="mt-10 border-t border-hv-border pt-6">
    <h2 id="research-library-title" className="text-xl font-bold">Triathlon research plans</h2>
    <p className="mt-1 text-sm text-hv-warning">Research Candidate · Sports-science review required · Not individualized medical advice</p>
    <div role="tablist" aria-label="Triathlon research plans" className="mt-4 flex flex-wrap gap-2">{triathlonResearchPlans.map(item => <button key={item.planId} role="tab" aria-selected={item.planId === selected} onClick={() => setSelected(item.planId)} className="rounded border border-hv-border px-3 py-2 focus-visible:ring-2 focus-visible:ring-hv-primary">{item.name}</button>)}</div>
    <article className="mt-4 rounded-lg border border-hv-border bg-hv-surface-1 p-4">
      <h3 className="font-semibold">{plan.name} — {plan.durationWeeks} weeks</h3>
      <h4 className="mt-3 font-medium">Prerequisites</h4><p className="text-sm text-hv-text-muted">{Array.isArray(plan.prerequisites) ? plan.prerequisites.join(" · ") : String(plan.prerequisites)}</p>
      <h4 className="mt-3 font-medium">Phase timeline</h4>
      {phaseTimeline.unavailable ? <p className="text-sm text-hv-text-muted">Phase details unavailable</p> : <><ol aria-label="Plan phase timeline" className="space-y-3 text-sm break-words">{phaseTimeline.entries.map((phase, index) => { const purpose = presentationSafePhasePurpose(phase.purpose); return <li key={`${phase.phaseId}-${phase.firstWeek}`} className="rounded border border-hv-border p-3"><h5 className="font-medium">{formatPhaseWeeks(phase)} — {phase.displayName}</h5><p className="mt-1 text-hv-text-muted">{[phase.recovery && "Recovery", phase.taper && "Taper", phase.event && "Event"].filter(Boolean).join(" · ") || "Training phase"}</p>{purpose.text ? <p className="mt-2">{purpose.text}</p> : null}{purpose.editorialDiagnostic ? <p className="mt-2 text-hv-warning">{purpose.editorialDiagnostic}</p> : null}<span className="sr-only">Timeline segment {index + 1}</span></li>; })}</ol><details className="mt-3"><summary>Phase technical details</summary><ul className="mt-2 list-disc pl-5 text-sm break-all">{phaseTimeline.definitions.map(phase => <li key={phase.phaseId}>{phase.phaseId}: {phase.displayName}; source {phase.source}; weeks {phase.weekNumbers.join(", ")}; source objective: {phase.purpose ?? "Not recorded"}</li>)}</ul></details></>}
      <h4 className="mt-3 font-medium">Discipline duration</h4><dl className="grid grid-cols-2 gap-x-3 text-sm">{activeDisciplineFields.map(([label]) => <div key={label} className="contents"><dt>{label}</dt><dd>{totals[label]} minutes</dd></div>)}</dl>
      <p className="mt-3 text-sm">Recovery weeks: {plan.weeks.filter(week => week.recoveryWeek).map(week => week.weekNumber).join(", ") || "None marked"}. Required sessions: {plan.weeks.flatMap(w => w.days).flatMap(d => d.assignments).filter(a => a.required && a.assignmentType !== "RACE").length}. Optional sessions: {plan.weeks.flatMap(w => w.days).flatMap(d => d.assignments).filter(a => !a.required).length}.</p>
      <details className="mt-3"><summary>Weeks, sessions and race placeholders</summary>{plan.weeks.map(week => <section key={week.weekNumber} aria-label={`Week ${week.weekNumber}`} className="mt-4"><h5 className="font-medium">Week {week.weekNumber} · {week.phaseName}{week.recoveryWeek ? " · Recovery" : ""}</h5><ul className="mt-2 space-y-3 text-sm">{week.days.filter(day => day.assignments.length).map(day => <li key={day.dayOfWeek}><h6 className="font-medium">{day.dayOfWeek}</h6><ol className="mt-1 space-y-2">{day.assignments.map(a => { const session = researchSessionPresentation(a.sessionId, triathlonResearchDataset.sessions); const showOrder = day.assignments.length > 1; return <li key={a.assignmentId} aria-label={`${day.dayOfWeek}: ${session.title}, ${session.duration}${showOrder ? `, session ${a.orderWithinDay} of ${day.assignments.length}` : ""}`} className="min-w-0 break-words">{showOrder ? <span className="font-medium">{a.orderWithinDay}. </span> : null}<span>{session.title}</span><span className="block text-hv-text-muted">{session.duration}{session.discipline ? ` · ${session.discipline}` : ""}{a.assignmentType === "OPTIONAL_SESSION" ? " · Optional" : ""}</span><details className="mt-1"><summary>Technical details</summary><span className="break-all">Session ID: {a.sessionId}; assignment ID: {a.assignmentId}</span></details></li>; })}</ol></li>)}</ul></section>)}</details>
      <details className="mt-3"><summary>Evidence and limitations</summary><p className="mt-2 text-sm">Evidence supports general training principles, not these exact Human V1 schedules.</p><ul className="mt-2 list-disc pl-5 text-sm space-y-2">{plan.evidenceReferenceIds.map(id => { const evidence = triathlonResearchDataset.evidenceCatalogue.find(item => item.evidenceId === id); return evidence ? <li key={id}><span>{evidence.title} — {evidenceDirectnessLabel(evidence.directness)}; {evidenceVerificationLabel(evidence.verificationStatus)}.</span><span className="block">Limitation: {evidence.limitations}</span><details><summary>Technical evidence values</summary>{evidence.directness}; {evidence.verificationStatus}; {id}</details></li> : null; })}</ul></details>
      {!mutationDisabled && <button type="button" data-testid={`create-research-copy-${plan.planId}`} aria-label={`Create editable cloud copy of ${plan.name}`} disabled={pending} onClick={() => setConfirming(true)} className="mt-4 rounded bg-hv-primary px-3 py-2 text-white focus-visible:ring-2 focus-visible:ring-hv-primary disabled:opacity-50">Create editable copy</button>}
      {confirming && <div role="dialog" aria-modal="true" aria-labelledby="research-copy-title" className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="max-w-md rounded-lg bg-hv-surface-1 p-5"><h4 id="research-copy-title" className="font-semibold">Create an editable cloud copy of {plan.name}?</h4><p className="mt-2 text-sm text-hv-text-muted">This creates new cloud data in your account. The Research Candidate source remains unchanged.</p><div className="mt-4 flex justify-end gap-3"><button type="button" onClick={() => setConfirming(false)}>Cancel</button><button type="button" disabled={pending} onClick={async () => { if (pending) return; setPending(true); try { await onClone(plan); } finally { setPending(false); setConfirming(false); } }} className="rounded bg-hv-primary px-3 py-2 text-white disabled:opacity-50">Create cloud copy of {plan.name}</button></div></div></div>}
    </article>
  </section>;
}
